// server/rte-react-js/src/App.jsx
import './App.css';

import { useRef, useState } from 'react';

import RichTextEditor from './RichTextEditor';
import {
  createStructuredContent,
  fromMarkdown,
  renderHTML,
  toMarkdown,
} from './richTextEditorBridge';

const welcomeDocument = `<h2>React wrapper demo</h2>
<p>This editor is mounted declaratively and the wrapper autoloads the RichTextEditor assets from <code>/richtexteditor</code>.</p>
<ul>
  <li>Controlled HTML value</li>
  <li>Live JSON snapshot</li>
  <li>No manual script tags in app code</li>
</ul>`;

const jsonDocument = {
  type: 'doc',
  version: 2,
  format: 'richtexteditor-json',
  content: [
    {
      type: 'heading',
      attrs: { level: 2 },
      content: [{ type: 'text', text: 'Structured payload' }],
    },
    {
      type: 'paragraph',
      content: [
        { type: 'text', text: 'This document was restored from a ' },
        { type: 'text', text: 'node-based', marks: [{ type: 'bold' }] },
        { type: 'text', text: ' JSON model instead of a plain HTML wrapper.' },
      ],
    },
    {
      type: 'bulletList',
      content: [
        {
          type: 'listItem',
          content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Heading node' }] }],
        },
        {
          type: 'listItem',
          content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Paragraph node' }] }],
        },
        {
          type: 'listItem',
          content: [{ type: 'paragraph', content: [{ type: 'text', text: 'List nodes with nested blocks' }] }],
        },
      ],
    },
    {
      type: 'blockquote',
      content: [
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'RichTextEditor still keeps HTML interoperability, but the document model is now semantic enough for app state and future APIs.',
            },
          ],
        },
      ],
    },
  ],
};

const markdownDocument = `## Markdown import

This starter can now restore content from **Markdown** and keep the semantic JSON model in sync.

- Headings
- Lists
- [Links](https://richtexteditor.com)

> Static rendering now works without a live editor instance.`;

const initialDocument = createStructuredContent(welcomeDocument);

function App() {
  const editorRef = useRef(null);
  const [htmlValue, setHtmlValue] = useState(initialDocument.html || welcomeDocument);
  const [jsonValue, setJsonValue] = useState(initialDocument);
  const [markdownValue, setMarkdownValue] = useState(toMarkdown(initialDocument));
  const [renderedHtml, setRenderedHtml] = useState(renderHTML(initialDocument));
  const [status, setStatus] = useState('Loading editor assets...');

  function syncDocument(documentModel, nextHtml) {
    const resolvedHtml = nextHtml !== undefined ? nextHtml : renderHTML(documentModel);
    setHtmlValue(resolvedHtml);
    setJsonValue(documentModel);
    setMarkdownValue(toMarkdown(documentModel));
    setRenderedHtml(renderHTML(documentModel));
  }

  function handleChange(nextHtml, editor) {
    syncDocument(editor.getJSON(), nextHtml);
  }

  function handleReady(editor) {
    syncDocument(editor.getJSON());
    setStatus('Editor ready');
  }

  function handleError(error) {
    setStatus(error.message);
  }

  function loadWelcome() {
    const documentModel = createStructuredContent(welcomeDocument);
    syncDocument(documentModel, welcomeDocument);
  }

  function loadJsonDocument() {
    if (editorRef.current) {
      editorRef.current.setJSON(jsonDocument);
      syncDocument(editorRef.current.getJSON(), editorRef.current.getHTMLCode());
    }
  }

  function loadMarkdownDocument() {
    const documentModel = fromMarkdown(markdownDocument);
    if (editorRef.current) {
      editorRef.current.setJSON(documentModel);
      syncDocument(editorRef.current.getJSON(), editorRef.current.getHTMLCode());
      return;
    }

    syncDocument(documentModel);
  }

  function focusEditor() {
    if (editorRef.current) {
      editorRef.current.focus();
    }
  }

  function refreshJson() {
    if (editorRef.current) {
      syncDocument(editorRef.current.getJSON(), editorRef.current.getHTMLCode());
    }
  }

  return (
    <main className="app-shell">
      <section className="hero">
        <div>
          <p className="eyebrow">v2.1 foundation</p>
          <h1>RichTextEditor for React</h1>
          <p className="lede">
            This starter uses a declarative wrapper with asset autoloading and a structured
            content bridge on top of the existing editor core.
          </p>
        </div>
        <div className="status-chip">{status}</div>
      </section>

      <section className="workspace">
        <div className="editor-card">
          <div className="toolbar-row">
            <button onClick={loadWelcome}>Load HTML sample</button>
            <button onClick={loadJsonDocument}>Load JSON sample</button>
            <button onClick={loadMarkdownDocument}>Load Markdown sample</button>
            <button onClick={refreshJson}>Refresh JSON</button>
            <button onClick={focusEditor}>Focus editor</button>
          </div>

          <RichTextEditor
            ref={editorRef}
            assetBasePath="/richtexteditor"
            className="editor-host"
            value={htmlValue}
            onChange={handleChange}
            onReady={handleReady}
            onError={handleError}
            style={{ minHeight: 380 }}
          />
        </div>

        <div className="preview-grid">
          <article className="preview-card">
            <h2>HTML output</h2>
            <textarea readOnly value={htmlValue} />
          </article>

          <article className="preview-card">
            <h2>Markdown output</h2>
            <textarea readOnly value={markdownValue} />
          </article>

          <article className="preview-card">
            <h2>JSON output</h2>
            <textarea readOnly value={JSON.stringify(jsonValue, null, 2)} />
          </article>

          <article className="preview-card">
            <h2>Static HTML render</h2>
            <div className="rendered-preview" dangerouslySetInnerHTML={{ __html: renderedHtml }} />
          </article>
        </div>
      </section>
    </main>
  );
}

export default App;

// server/rte-ng-ts/src/app/app.component.ts
import { Component, ViewChild } from '@angular/core';

import {
  createStructuredContent,
  fromMarkdown,
  renderHTML,
  RichTextEditorStructuredDocument,
  toMarkdown,
} from './rich-text-editor-bridge';
import {
  RichTextEditorChangeEvent,
  RichTextEditorComponent,
} from './rich-text-editor.component';

const createWelcomeDocument = (): RichTextEditorStructuredDocument => ({
  type: 'doc',
  version: 2,
  format: 'richtexteditor-json',
  content: [
    {
      type: 'heading',
      attrs: { level: 2 },
      content: [{ type: 'text', text: 'Angular wrapper demo' }],
    },
    {
      type: 'paragraph',
      content: [
        { type: 'text', text: 'This starter uses a reusable Angular component instead of manually instantiating ' },
        { type: 'text', text: 'window.RichTextEditor', marks: [{ type: 'code' }] },
        { type: 'text', text: ' inside the app component.' },
      ],
    },
    {
      type: 'bulletList',
      content: [
        {
          type: 'listItem',
          content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Declarative wrapper' }] }],
        },
        {
          type: 'listItem',
          content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Asset autoloading' }] }],
        },
        {
          type: 'listItem',
          content: [{ type: 'paragraph', content: [{ type: 'text', text: 'JSON bridge for app state' }] }],
        },
      ],
    },
  ],
});

const createAlternateDocument = (): RichTextEditorStructuredDocument => ({
  type: 'doc',
  version: 2,
  format: 'richtexteditor-json',
  content: [
    {
      type: 'heading',
      attrs: { level: 2 },
      content: [{ type: 'text', text: 'Structured content restored' }],
    },
    {
      type: 'paragraph',
      content: [
        { type: 'text', text: 'The Angular starter can restore content from ' },
        { type: 'text', text: 'setJSON()', marks: [{ type: 'code' }] },
        { type: 'text', text: ' and keep a semantic document snapshot in component state.' },
      ],
    },
    {
      type: 'blockquote',
      content: [
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'That brings Angular to the same integration level as the React and Vue demos.',
            },
          ],
        },
      ],
    },
  ],
});

const markdownDocument = `## Markdown import

This Angular starter can restore **Markdown** into the shared JSON model.

- Markdown
- Structured state
- Static HTML rendering

> That keeps Angular aligned with the React and Vue demos.`;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  @ViewChild('editorRef') editorComponent?: RichTextEditorComponent;

  title = 'RichTextEditor for Angular';
  documentModel: RichTextEditorStructuredDocument = createWelcomeDocument();
  status = 'Loading editor assets...';

  get htmlPreview(): string {
    return this.documentModel.html || '';
  }

  get jsonPreview(): string {
    return JSON.stringify(this.documentModel, null, 2);
  }

  get markdownPreview(): string {
    return toMarkdown(this.documentModel);
  }

  get renderedPreview(): string {
    return renderHTML(this.documentModel);
  }

  handleEditorChange(event: RichTextEditorChangeEvent): void {
    this.documentModel =
      typeof event.value === 'string' ? createStructuredContent(event.value) : event.value;
  }

  handleEditorReady(editor: { getJSON(): RichTextEditorStructuredDocument }): void {
    this.documentModel = editor.getJSON();
    this.status = 'Editor ready';
  }

  handleEditorError(error: Error): void {
    this.status = error.message;
  }

  loadWelcomeDocument(): void {
    this.documentModel = createWelcomeDocument();
  }

  loadStructuredDocument(): void {
    this.documentModel = createAlternateDocument();
  }

  loadMarkdownDocument(): void {
    this.documentModel = fromMarkdown(markdownDocument);
  }

  focusEditor(): void {
    this.editorComponent?.focus();
  }
}

<main class="app-shell">
  <section class="hero">
    <div>
      <p class="eyebrow">v2.1 foundation</p>
      <h1>{{ title }}</h1>
      <p class="lede">
        This Angular starter now uses a reusable wrapper component, automatic asset loading,
        and the same JSON bridge format as the React and Vue demos.
      </p>
    </div>
    <div class="status-chip">{{ status }}</div>
  </section>

  <section class="workspace">
    <article class="editor-card">
      <div class="toolbar-row">
        <button (click)="loadWelcomeDocument()">Load welcome doc</button>
        <button (click)="loadStructuredDocument()">Load JSON sample</button>
        <button (click)="loadMarkdownDocument()">Load Markdown sample</button>
        <button (click)="focusEditor()">Focus editor</button>
      </div>

      <app-rich-text-editor
        #editorRef
        class="editor-frame"
        [assetBasePath]="'/assets/richtexteditor'"
        [value]="documentModel"
        [valueFormat]="'json'"
        (change)="handleEditorChange($event)"
        (ready)="handleEditorReady($event)"
        (error)="handleEditorError($event)"
      ></app-rich-text-editor>
    </article>

    <div class="preview-grid">
      <article class="preview-card">
        <h2>HTML output</h2>
        <textarea [value]="htmlPreview" readonly></textarea>
      </article>

      <article class="preview-card">
        <h2>Markdown output</h2>
        <textarea [value]="markdownPreview" readonly></textarea>
      </article>

      <article class="preview-card">
        <h2>JSON output</h2>
        <textarea [value]="jsonPreview" readonly></textarea>
      </article>

      <article class="preview-card">
        <h2>Static HTML render</h2>
        <div class="rendered-preview" [innerHTML]="renderedPreview"></div>
      </article>
    </div>
  </section>
</main>
