// server/rte-vue-js/src/components/RichTextEditor.vue
<script setup>
import { onBeforeUnmount, onMounted, ref, watch } from "vue";

import { loadRichTextEditorAssets, normalizeStructuredContent } from "../richTextEditorBridge";

const props = defineProps({
  assetBasePath: {
    type: String,
    default: "/richtexteditor",
  },
  config: {
    type: Object,
    default: () => ({}),
  },
  defaultValue: {
    type: [String, Object],
    default: undefined,
  },
  modelValue: {
    type: [String, Object],
    default: undefined,
  },
  valueFormat: {
    type: String,
    default: "html",
  },
});

const emit = defineEmits(["change", "error", "ready", "update:modelValue"]);

const hostRef = ref(null);
const editorRef = ref(null);

let changeHandler = null;

function syncEditor(nextValue) {
  if (!editorRef.value) {
    return;
  }

  const nextHtml = normalizeStructuredContent(nextValue);
  if (editorRef.value.getHTMLCode() !== nextHtml) {
    if (props.valueFormat === "json") {
      editorRef.value.setJSON(nextValue);
    } else {
      editorRef.value.setHTMLCode(nextHtml);
    }
  }
}

function getEditor() {
  return editorRef.value;
}

defineExpose({
  focus() {
    if (editorRef.value) {
      editorRef.value.focus();
    }
  },
  getEditor,
  getHTMLCode() {
    return editorRef.value ? editorRef.value.getHTMLCode() : "";
  },
  getJSON() {
    return editorRef.value ? editorRef.value.getJSON() : null;
  },
  setHTMLCode(nextValue) {
    if (editorRef.value) {
      editorRef.value.setHTMLCode(nextValue || "");
    }
  },
  setJSON(nextValue) {
    if (editorRef.value) {
      editorRef.value.setJSON(nextValue);
    }
  },
});

onMounted(async () => {
  try {
    await loadRichTextEditorAssets(props.assetBasePath);

    if (!hostRef.value) {
      return;
    }

    const editor = new window.RichTextEditor(hostRef.value, props.config || {});
    editorRef.value = editor;

    const initialValue = props.modelValue !== undefined ? props.modelValue : props.defaultValue;
    if (initialValue !== undefined) {
      if (props.valueFormat === "json") {
        editor.setJSON(initialValue);
      } else {
        editor.setHTMLCode(normalizeStructuredContent(initialValue));
      }
    }

    changeHandler = () => {
      const nextValue = props.valueFormat === "json" ? editor.getJSON() : editor.getHTMLCode();
      emit("update:modelValue", nextValue);
      emit("change", nextValue, editor);
    };

    editor.attachEvent("change", changeHandler);
    emit("ready", editor);
  } catch (error) {
    emit("error", error);
  }
});

watch(
  () => props.modelValue,
  (nextValue) => {
    if (props.modelValue === undefined) {
      return;
    }

    syncEditor(nextValue);
  },
  { deep: true }
);

watch(
  () => props.valueFormat,
  () => {
    if (props.modelValue === undefined) {
      return;
    }

    syncEditor(props.modelValue);
  }
);

onBeforeUnmount(() => {
  if (editorRef.value && changeHandler && typeof editorRef.value.detachEvent === "function") {
    editorRef.value.detachEvent("change", changeHandler);
  }

  if (hostRef.value) {
    hostRef.value.innerHTML = "";
  }

  editorRef.value = null;
});
</script>

<template>
  <div ref="hostRef" class="editor-host"></div>
</template>

// server/rte-ng-ts/src/app/rich-text-editor.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  Output,
  SimpleChanges,
  ViewChild,
} from '@angular/core';

import {
  RichTextEditorInput,
  RichTextEditorInstance,
  RichTextEditorStructuredDocument,
  RichTextEditorValueFormat,
  loadRichTextEditorAssets,
  normalizeStructuredContent,
} from './rich-text-editor-bridge';

export interface RichTextEditorChangeEvent {
  editor: RichTextEditorInstance;
  value: string | RichTextEditorStructuredDocument;
}

@Component({
  selector: 'app-rich-text-editor',
  template: '<div #host class="editor-host"></div>',
  styles: [
    `
      :host {
        display: block;
        min-height: 380px;
      }

      .editor-host {
        min-height: 380px;
        border-radius: 18px;
        overflow: hidden;
      }
    `,
  ],
})
export class RichTextEditorComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input() assetBasePath = '/assets/richtexteditor';
  @Input() config: Record<string, unknown> = {};
  @Input() value: RichTextEditorInput | null = null;
  @Input() valueFormat: RichTextEditorValueFormat = 'html';

  @Output() change = new EventEmitter<RichTextEditorChangeEvent>();
  @Output() error = new EventEmitter<Error>();
  @Output() ready = new EventEmitter<RichTextEditorInstance>();

  @ViewChild('host', { static: true }) hostRef!: ElementRef<HTMLDivElement>;

  private changeHandler: (() => void) | null = null;
  private editor: RichTextEditorInstance | null = null;

  async ngAfterViewInit(): Promise<void> {
    try {
      await loadRichTextEditorAssets(this.assetBasePath);

      this.editor = new window.RichTextEditor!(this.hostRef.nativeElement, this.config || {});

      if (this.value !== null && this.value !== undefined) {
        this.syncEditor(this.value);
      }

      this.changeHandler = () => {
        if (!this.editor) {
          return;
        }

        const nextValue =
          this.valueFormat === 'json' ? this.editor.getJSON() : this.editor.getHTMLCode();
        this.change.emit({ editor: this.editor, value: nextValue });
      };

      this.editor.attachEvent('change', this.changeHandler);
      this.ready.emit(this.editor);
    } catch (loadError) {
      this.error.emit(loadError as Error);
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (!this.editor) {
      return;
    }

    if (changes['value'] || changes['valueFormat']) {
      this.syncEditor(this.value);
    }
  }

  ngOnDestroy(): void {
    if (this.editor && this.changeHandler && typeof this.editor.detachEvent === 'function') {
      this.editor.detachEvent('change', this.changeHandler);
    }

    this.hostRef.nativeElement.innerHTML = '';
    this.editor = null;
    this.changeHandler = null;
  }

  focus(): void {
    if (this.editor) {
      this.editor.focus();
    }
  }

  getEditor(): RichTextEditorInstance | null {
    return this.editor;
  }

  getHTMLCode(): string {
    return this.editor ? this.editor.getHTMLCode() : '';
  }

  getJSON(): RichTextEditorStructuredDocument | null {
    return this.editor ? this.editor.getJSON() : null;
  }

  setHTMLCode(value: string): void {
    if (this.editor) {
      this.editor.setHTMLCode(value || '');
    }
  }

  setJSON(value: RichTextEditorInput): void {
    if (this.editor) {
      this.editor.setJSON(value);
    }
  }

  private syncEditor(nextValue: RichTextEditorInput | null): void {
    if (!this.editor || nextValue === null || nextValue === undefined) {
      return;
    }

    const nextHtml = normalizeStructuredContent(nextValue);
    if (this.editor.getHTMLCode() !== nextHtml) {
      if (this.valueFormat === 'json') {
        this.editor.setJSON(nextValue);
      } else {
        this.editor.setHTMLCode(nextHtml);
      }
    }
  }
}
