// server/rte-vue-js/src/components/RichTextEditor.vue
<script setup>
import { onBeforeUnmount, onMounted, ref, watch } from "vue";

import { loadRichTextEditorAssets, normalizeStructuredContent } from "../richTextEditorBridge";

const props = defineProps({
  assetBasePath: {
    type: String,
    default: "/richtexteditor",
  },
  config: {
    type: Object,
    default: () => ({}),
  },
  defaultValue: {
    type: [String, Object],
    default: undefined,
  },
  modelValue: {
    type: [String, Object],
    default: undefined,
  },
  valueFormat: {
    type: String,
    default: "html",
  },
});

const emit = defineEmits(["change", "error", "ready", "update:modelValue"]);

const hostRef = ref(null);
const editorRef = ref(null);

let changeHandler = null;

function syncEditor(nextValue) {
  if (!editorRef.value) {
    return;
  }

  const nextHtml = normalizeStructuredContent(nextValue);
  if (editorRef.value.getHTMLCode() !== nextHtml) {
    if (props.valueFormat === "json") {
      editorRef.value.setJSON(nextValue);
    } else {
      editorRef.value.setHTMLCode(nextHtml);
    }
  }
}

function getEditor() {
  return editorRef.value;
}

defineExpose({
  focus() {
    if (editorRef.value) {
      editorRef.value.focus();
    }
  },
  getEditor,
  getHTMLCode() {
    return editorRef.value ? editorRef.value.getHTMLCode() : "";
  },
  getJSON() {
    return editorRef.value ? editorRef.value.getJSON() : null;
  },
  setHTMLCode(nextValue) {
    if (editorRef.value) {
      editorRef.value.setHTMLCode(nextValue || "");
    }
  },
  setJSON(nextValue) {
    if (editorRef.value) {
      editorRef.value.setJSON(nextValue);
    }
  },
});

onMounted(async () => {
  try {
    await loadRichTextEditorAssets(props.assetBasePath);

    if (!hostRef.value) {
      return;
    }

    const editor = new window.RichTextEditor(hostRef.value, props.config || {});
    editorRef.value = editor;

    const initialValue = props.modelValue !== undefined ? props.modelValue : props.defaultValue;
    if (initialValue !== undefined) {
      if (props.valueFormat === "json") {
        editor.setJSON(initialValue);
      } else {
        editor.setHTMLCode(normalizeStructuredContent(initialValue));
      }
    }

    changeHandler = () => {
      const nextValue = props.valueFormat === "json" ? editor.getJSON() : editor.getHTMLCode();
      emit("update:modelValue", nextValue);
      emit("change", nextValue, editor);
    };

    editor.attachEvent("change", changeHandler);
    emit("ready", editor);
  } catch (error) {
    emit("error", error);
  }
});

watch(
  () => props.modelValue,
  (nextValue) => {
    if (props.modelValue === undefined) {
      return;
    }

    syncEditor(nextValue);
  },
  { deep: true }
);

watch(
  () => props.valueFormat,
  () => {
    if (props.modelValue === undefined) {
      return;
    }

    syncEditor(props.modelValue);
  }
);

onBeforeUnmount(() => {
  if (editorRef.value && changeHandler && typeof editorRef.value.detachEvent === "function") {
    editorRef.value.detachEvent("change", changeHandler);
  }

  if (hostRef.value) {
    hostRef.value.innerHTML = "";
  }

  editorRef.value = null;
});
</script>

<template>
  <div ref="hostRef" class="editor-host"></div>
</template>

// server/rte-react-js/src/RichTextEditor.jsx
import { forwardRef, useEffect, useImperativeHandle, useRef } from "react";

import {
  loadRichTextEditorAssets,
  normalizeStructuredContent,
} from "./richTextEditorBridge";

const RichTextEditor = forwardRef(function RichTextEditor(
  {
    assetBasePath = "/richtexteditor",
    config,
    defaultValue,
    onChange,
    onError,
    onReady,
    value,
    valueFormat = "html",
    ...divProps
  },
  forwardedRef
) {
  const hostRef = useRef(null);
  const editorRef = useRef(null);
  const onChangeRef = useRef(onChange);
  const onReadyRef = useRef(onReady);
  const onErrorRef = useRef(onError);
  const valueFormatRef = useRef(valueFormat);
  const configRef = useRef(config || {});
  const initialValueRef = useRef(value !== undefined ? value : defaultValue);

  useEffect(() => {
    onChangeRef.current = onChange;
    onReadyRef.current = onReady;
    onErrorRef.current = onError;
    valueFormatRef.current = valueFormat;
    configRef.current = config || {};
  });

  useImperativeHandle(
    forwardedRef,
    () => ({
      getEditor: () => editorRef.current,
      focus: () => {
        if (editorRef.current) {
          editorRef.current.focus();
        }
      },
      getJSON: () => (editorRef.current ? editorRef.current.getJSON() : null),
      setJSON: (nextValue) => {
        if (editorRef.current) {
          editorRef.current.setJSON(nextValue);
        }
      },
      getHTMLCode: () => (editorRef.current ? editorRef.current.getHTMLCode() : ""),
      setHTMLCode: (nextValue) => {
        if (editorRef.current) {
          editorRef.current.setHTMLCode(nextValue || "");
        }
      },
    }),
    []
  );

  useEffect(() => {
    let disposed = false;
    let changeHandler = null;
    const activeHost = hostRef.current;

    loadRichTextEditorAssets(assetBasePath)
      .then(() => {
        if (disposed || !activeHost) {
          return;
        }

        const editor = new window.RichTextEditor(activeHost, configRef.current);
        editorRef.current = editor;

        const initialValue = initialValueRef.current;
        if (initialValue !== undefined) {
          if (valueFormatRef.current === "json") {
            editor.setJSON(initialValue);
          } else {
            editor.setHTMLCode(normalizeStructuredContent(initialValue));
          }
        }

        changeHandler = () => {
          if (!onChangeRef.current) {
            return;
          }

          const nextValue =
            valueFormatRef.current === "json" ? editor.getJSON() : editor.getHTMLCode();
          onChangeRef.current(nextValue, editor);
        };

        editor.attachEvent("change", changeHandler);

        if (onReadyRef.current) {
          onReadyRef.current(editor);
        }
      })
      .catch((error) => {
        if (!disposed && onErrorRef.current) {
          onErrorRef.current(error);
        }
      });

    return () => {
      disposed = true;

      if (editorRef.current && changeHandler && typeof editorRef.current.detachEvent === "function") {
        editorRef.current.detachEvent("change", changeHandler);
      }

      if (activeHost) {
        activeHost.innerHTML = "";
      }

      editorRef.current = null;
    };
  }, [assetBasePath]);

  useEffect(() => {
    if (!editorRef.current || value === undefined) {
      return;
    }

    const nextHtml = normalizeStructuredContent(value);
    if (editorRef.current.getHTMLCode() !== nextHtml) {
      if (valueFormat === "json") {
        editorRef.current.setJSON(value);
      } else {
        editorRef.current.setHTMLCode(nextHtml);
      }
    }
  }, [value, valueFormat]);

  return <div {...divProps} ref={hostRef} />;
});

export default RichTextEditor;
